setwd("~/Desktop/data_analysis/Final project/Develish-Data-Demons")

library(tidyverse)

creator_data <- read_csv("creator_data.csv") 
birthDate_data <- count(creator_data, birthDate)
birthYear_data <- count(creator_data, birthYear)
deathDate_data <- count(creator_data, deathDate)
deathYear_data <- count(creator_data, deathYear)
ethnicity_data <- count(creator_data, ethnicity)
nationality_data <- count(creator_data, nationality)
country_data <- count(creator_data, country)
region_data <- count(creator_data, region)
religion_data <- count(creator_data, religion)
activeYearsStartYear_data <- count(activeYearsStartYear_data, religion)
genre_data <- count(creator_data, genre)
notableWork_data <- count(creator_data, notableWork)
almaMater_data <- count(creator_data, almaMater)
gender_data <- count(creator_data, Gender)